### PR TITLE
Cleanup deprecated and removed entries in index

### PR DESCRIPTION
**Pull request by jjhursey**
* The deprecated and removed items appear after the normative items.
 * All in their respective indices.
 * Fix up `check-attr-refs.py` to check for deprecated and removed
   items that have references in the document which indicates that
   they were not completely removed.

### CODE REVIEW

**Comment by jjhursey** [comment]
I started this because I was looking for an attribute in the index, but kept seeing the deprecated/removed items intermixed. This was confusing to me. So I decided to split them out.

This PR will place the deprecated/removed items at the bottom of their respective indices. Additionally, this strengthens the `./bin/check-attr-refs.py` document check for attributes.

Below is a preview of what it looks like now.
image

**Comment by jjhursey** [comment]
I just posted a new commit that fixes the "removed but not deprecated" listing of constants. So this is ready for a review. Once merged I'll cherry-pick them to the v4 branch.

**Comment by jjhursey** [comment]
! found two more deprecated references to fix. This is good for review now.

**Review by rhc54 — APPROVED** [review]
Thanks Josh!

**Pull request merged**
