### PR TITLE
MPI Sessions Use-case

### PR DESCRIPTION
**Pull request by spophale**
Please use emoji reactions ON THIS COMMENT to indicate your position on this proposal.

* You do not need to vote on every proposal
* If you have no opinion, don't vote - that is also useful data
* If you've already commented on this issue, please still vote so
      we know your current thoughts
* Not all proposals solve exactly the same problem, so we may end
      up accepting proposals that appear to have some overlap
This is not a binding majority-rule vote, but it will be a very
significant input into the corresponding ASC decision.

Here are the meanings for the emojis:

* Hooray or Rocket: I support this so strongly that I
      want to be an advocate for it
* Heart: I think this is an ideal solution
* Thumbs up: I'd be happy with this solution
* Confused: I'd rather we not do this, but I can tolerate it
* Thumbs down: I'd be actively unhappy, and may even consider
      other technologies instead
If you want to explain in more detail, feel free to add another
comment, but please also vote on this comment.

### CODE REVIEW

**Comment by SteVwonder** [comment]
PDF copy of the standard as produced by the PR (updated 2021-04-14): [pmix-standard.pdf](https://github.com/pmix/pmix-standard/files/6312616/pmix-standard.pdf)

**Comment by jjhursey** [comment]
Note this PR requires PR #328 (which is up for a second vote in 2Q 2021). As such the first 13 commits to this PR are PR #328 and the 3 newer commits are actually part of this PR.

**Comment by jjhursey** [comment]
PMIx ASC 2Q 2021
 * Passed the first vote: 7 yes / 0 no / 1 abstain
 * Eligible for the second vote 3Q 2021
 * Once https://github.com/pmix/pmix-standard/pull/328 is merged then you can rebase this PR. Thanks!

**Comment by jjhursey** [comment]
Now that PR #328 has been merged I:
 * Rebased this PR (since it was based on PR #328 
 * Add `Signed-off-by: Swaroop Pophale <swaroop.pophale23@gmail.com>` to the PRs.
   * @spophale Please confirm that is an ok change with you.
 * No other changes were made.

**Comment by jjhursey** [comment]
PMIx ASC 3Q 2021
 * Passed the second vote: 7 yes / 0 no / 2 abstain
 * Will be merged into the master branch targeting PMIx v5.0

**Review by jjhursey — APPROVED** [review]

**Comment by jjhursey** [comment]
I rebased and merged this PR. It'll be in the v5 version of the document.

**Pull request merged**
