### PR TITLE
Issue420/get nb key@v5

### LINKED ISSUE #420: Parameter Conflict: PMIx_Get vs PMIx_Get_nb
PMIx_Get has a signature that includes `const pmix_key_t key`.

PMIx_Get_nb has a signature that includes `const char key[]` for the same argument.

The problem is that these conflict in the eyes of today's picky compilers such as gcc12, which will generate a warning if:

* you pass a `char*` string to PMIx_Get, but not if you pass that same string to PMIx_Get_nb.
* you pass a `pmix_key_t` to PMIx_Get_nb, but not if you pass that same key to PMIx_Get

So which is it supposed to be?

### PR DESCRIPTION
**Pull request by abouteiller**
Import changes from v4.2 to v5.1

#491
closes #420 

* [x] waiting on #488 merged in v4
* [x] review openPMIx for conformity with proposed change: NOT CONFORMANT
* [x] review v4.2 and potential need to rollback #488 ? NEED TO ROLLBACK

### CODE REVIEW

**Review by raffenet — DISMISSED** [review]

**Comment by raffenet** [comment]
OK, after I clicked approve I went and double checked the OpenPMIx and see that neither API there uses `pmix_key_t`. I forget if this was discussed when we proposed the change?
```c
PMIX_EXPORT pmix_status_t PMIx_Get(const pmix_proc_t *proc, const char key[],
                                   const pmix_info_t info[], size_t ninfo,
                                   pmix_value_t **val);
PMIX_EXPORT pmix_status_t PMIx_Get_nb(const pmix_proc_t *proc, const char key[],
                                      const pmix_info_t info[], size_t ninfo,
                                      pmix_value_cbfunc_t cbfunc, void *cbdata);
```

**Comment by rhc54** [comment]
Yeah, you can't make it a `pmix_key_t` as the `key` parameter can be `NULL` - and IIRC, the compiler will complain if it is declared as a `pmix_key_t` in that instance.

**Comment by abouteiller** [comment]
We need to double check what happened with #488 as this is when we voted on it. The way that was understood (see #420) the implementation was already using the pmix_key_t and one of the procedures took it as such.

**Comment by rhc54** [comment]
> implementation was already using the pmix_key_t and one of the procedures took it as such.

Correct - and as I stated in #420, we corrected it to both APIs using `const char key[]`. Otherwise, you cannot pass a `NULL` argument, which would break some of the rules for `PMIx_Get`

**Comment by abouteiller** [comment]
I did exactly the wrong fix... Good that we caught that before it went out the door. I'll update #420 and we will have to revote on it, I'll check if that'll delay v4.2 based on our rules but I think it will.

**Comment by abouteiller** [comment]
This will now need to mirror #510

**Review by raffenet — APPROVED** [review]

**Pull request merged**
