### PR TITLE
Check: Add triage file for check-openpmix.py

### PR DESCRIPTION
**Pull request by jjhursey**
Run as:
```
./bin/check-openpmix.py -t etc/triage-in-openpmix-not-in-std.txt
```

### CODE REVIEW

**Comment by jjhursey** [comment]
I went through the list of missing symbols. I used `git blame` in OpenPMix to pull the commit ID where that symbol was last touched to get us a starting point.

I then created the triage file with these symbols grouped by commit hash. I'm hoping that this triage file will be a good starting point for us to group the missing symbols and then track a path for them back to the standard.

**Review by rhc54 — APPROVED** [review]
Looks reasonable to me

**Comment by jjhursey** [comment]
See note and PR https://github.com/openpmix/pmix-tests/pull/155#issuecomment-1419830524 about moving this functionality to `pmix-tests` in OpenPMix.

**Comment by jjhursey** [comment]
This script has been moved to pmix-tests

**Pull request closed without merging**
