### PR TITLE
Add provisional markers to storage chapter

### PR DESCRIPTION
**Pull request by jjhursey**

### CODE REVIEW

**Comment by jjhursey** [comment]
@shanedsnyder This PR adds the provisional markers for the storage chapter and adds a section to the revisions appendix for the new items. Can you take a look and give it a 👍  if it looks good to you?

I'm aware of a slight glitch in the provisional markers on page 3 of the storage chapter (pdf page 453) where the provisional marker in the margin does not appear for `PMIX_STORAGE_PERSISTENCE_ARCHIVE` and `pmix_storage_access_type_t`. That's nothing to hold up this PR. I'll see if I can figure out what's going on there out-of-band.

Once this is merged then I'll PR #280 and this to the `v4.x` branch.

**Review by abouteiller — APPROVED** [review]

**Comment by jjhursey** [comment]
@shanedsnyder Have you had a chance to take a look at this change to the Storage chapter? Any objection to merging this?

**Comment by shanedsnyder** [comment]
Sorry, I've been out of the office the last couple of days, but just had a look. Looks good to me, thanks!

**Comment by jjhursey** [comment]
Thanks! I'll merge and cherry-pick the storage changes to v4.0.x branch

**Pull request merged**
