### PR TITLE
Add Provisional Markers

### PR DESCRIPTION
**Pull request by jjhursey**
Add a mechanism for labeling provisional items and text segments. Also cleanup the style sheet a bit with some comments.

```
\provisionalMarker     Add a provisional label to the margin
\markProvisional       Add a provisional label to the margin and highlight the provided text

\declareconstitemProvisional  Declare Constant - Provisional
\declareEnvarProvisional      Declare Envar - Provisional
\declareAttributeProvisional  Declare Attribute - Provisional
```

### CODE REVIEW

**Comment by jjhursey** [comment]
v4 version of PR #337

**Comment by rhc54** [comment]
Well now, this is new:
```text
anyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading:
https://www.docker.com/increase-rate-limit

The command "docker pull jjhursey/pmix-standard" failed and exited with 1 during
```

**Comment by jjhursey** [comment]
Humm that shouldn't happen (I have the 'unlimited' plan) Let me check.

**Comment by jjhursey** [comment]
The rate limit issue is much bigger than I thought. I'll have to dig a bit to fix a resolution. It's looking like most people resolved the issue by abandoning Travis and moving to GitHub Actions.

**Comment by jjhursey** [comment]
We will need this merged before we can merge PR #280

**Comment by jjhursey** [comment]
@rhc54 Can you give this a review as a v4 RM so we can merge? #337 has an example rendering. Thanks!

**Review by rhc54 — APPROVED** [review]
The sample output looks fine to me, so I trust the implementation

**Pull request merged**
